# AWE worker with CWL runner

# docker build -t mgrast/awe-worker -f Dockerfile_worker .


FROM golang:1.7.6-alpine

# git needed for GIT_COMMIT_HASH
RUN apk update && apk add git

ENV AWE=/go/src/github.com/MG-RAST/AWE
WORKDIR /go/bin

COPY . /go/src/github.com/MG-RAST/AWE

# backwards compatible pathing with old dockerfile
RUN ln -s /go /gopath

# compile AWE
RUN mkdir -p ${AWE} && \
  cd ${AWE} && \
  go get -d ./awe-worker/ && \
  ./compile-worker.sh

# RUN apk update ; apk add \
#   gcc \
#   git \
#   libxml2-dev \
#   libxslt-dev \
#   musl-dev \
#   nodejs \
#   python-dev \
#   py-libxml2 \
#   py-pip \
#   py-psutil   

# install cwl-runner with node.js
RUN apk update ; apk add py-pip nodejs gcc python-dev musl-dev libxml2-dev libxslt-dev py-libxml2 py-psutil   
RUN pip install --upgrade pip ;  pip install cwltool==1.0.20180820141117 ; ln -s /usr/bin/cwltool /usr/bin/cwl-runner      # cwl-runner was pointing to old version 
RUN pip uninstall ruamel.yaml ; pip install ruamel.yaml==0.15.48