# This Dockerfile creates an environment for development purposes (this is not production)

# docker build -t mgrast/awe-worker -f Dockerfile_worker-develop .


FROM golang:1.7.4-alpine

# git needed for GIT_COMMIT_HASH
RUN apk update && apk add git

ENV AWE=/go/src/github.com/MG-RAST/AWE
WORKDIR /go/bin

COPY . /go/src/github.com/MG-RAST/AWE

# backwards compatible pathing with old dockerfile
RUN ln -s /go /gopath

# compile AWE
RUN mkdir -p ${AWE} && \
  cd ${AWE} && \
  go get -d ./awe-worker/ && \
  ./compile.sh

# install cwl-runner with node.js
RUN apk update ; apk add py-pip nodejs gcc python-dev musl-dev 
RUN pip install --upgrade pip ; pip install cwl-runner


