[job]
name:sample1_test
owner:wtang
totaltask: 4

[task-0]
totalwork: 1
cmd_name:FragGeneScan.pl
cmd_description: gene calling
cmd_args: -gnome=$input_1 -out=$output_1 -complete=0 -train=complete
inputs: "input_url1", "input_url2"
outputs: "fgs_output"
dependOn: 

[task-1]
totalwork: 1
cmd_name:Clustgun
cmd_description: clustering and amino acid assembly
cmd_args: -a
inputs: "fgs_output"
outputs: "clustgun_output"
dependOn: 0

[task-2]
totalwork: 1
cmd_name:SuperBlat
cmd_description: similarity search using parallel Blat
cmd_args: -c 4
inputs: "clustgun_output"
outputs: "blat_output"
dependOn: 1

[task-3]
totalwork: 1
cmd_name:hhsearch
cmd_description: HHM-based homology detect using HHpred
cmd_args: -c 4
inputs: "blat_output"
outputs: "hhrepd_output"
dependOn: 2
